arm_vel_controller:
   type: velocity_controllers/JointGroupVelocityController
   joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
   gains:
     shoulder_pan_joint: {p: 100,  i: 0.01, d: 10.0}
     shoulder_lift_joint: {p: 100,  i: 0.01, d: 10.0}
     elbow_joint: {p: 100,  i: 0.01, d: 10.0}
     wrist_1_joint: {p: 100,  i: 0.01, d: 10.0}
     wrist_2_joint: {p: 100,  i: 0.01, d: 10.0}
     wrist_3_joint: {p: 100,  i: 0.01, d: 10.0}

gazebo_ros_control:
  pid_gains:
    shoulder_pan_joint: {p: 100.0, i: 0.01, d: 10}
    shoulder_lift_joint: {p: 100.0, i: 0.01, d: 10}
    elbow_joint: {p: 100.0, i: 0.01, d: 10}
    wrist_1_joint: {p: 100.0, i: 0.01, d: 10}
    wrist_2_joint: {p: 100.0, i: 0.01, d: 10}
    wrist_3_joint: {p: 100.0, i: 0.01, d: 10}
        
